version: '3'

services:
    db:
        image: mysql:latest
        container_name: laravel-db
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
